import { Router } from 'express';
import * as mem from '../lib/memory.js';
const router = Router();
router.post('/sessions', async (req,res) => { try{res.status(201).json(await mem.createSession(req.body));}catch(e){res.status(500).json({error:(e as Error).message});} });
router.get('/sessions', async (req,res) => { const uid=String(req.query.user_id??''); if (!uid) return res.status(400).json({error:'user_id required'}); try{res.json(await mem.listSessions(uid,Number(req.query.limit??20)));}catch(e){res.status(500).json({error:(e as Error).message});} });
router.get('/sessions/:id', async (req,res) => { try{const s=await mem.getSession(req.params.id);if(!s)return res.status(404).json({error:'Not found'});res.json(s);}catch(e){res.status(500).json({error:(e as Error).message});} });
router.delete('/sessions/:id', async (req,res) => { try{await mem.archiveSession(req.params.id);res.json({ok:true});}catch(e){res.status(500).json({error:(e as Error).message});} });
router.get('/sessions/:id/messages', async (req,res) => { try{res.json(await mem.getMessages(req.params.id,Number(req.query.limit??100)));}catch(e){res.status(500).json({error:(e as Error).message});} });
router.post('/sessions/:id/messages', async (req,res) => { try{res.status(201).json(await mem.addMessage({session_id:req.params.id,...req.body}));}catch(e){res.status(500).json({error:(e as Error).message});} });
export default router;
